# Generated by Django 3.2.24 on 2024-02-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('descripcion', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('descripcion', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Terreno', 'Terreno')], max_length=15)),
                ('ubicacion', models.CharField(max_length=144)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=1000000000)),
                ('descripcion', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendida', 'Vendida'), ('Reservado', 'Reservado')], max_length=25)),
                ('caracteristicas', models.ManyToManyField(to='crea_admin.Caracteristicas')),
                ('servicios', models.ManyToManyField(to='crea_admin.Servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('apellido', models.CharField(max_length=144)),
                ('telefono', models.CharField(max_length=144)),
                ('correo', models.EmailField(max_length=144)),
                ('intereses', models.ManyToManyField(to='crea_admin.Propiedad')),
            ],
        ),
    ]
