# Generated by Django 5.0.2 on 2024-02-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crea_admin', '0002_alter_propiedad_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='nombre',
            field=models.CharField(choices=[('Habitaciones', 'Habitaciones'), ('Baños', 'Baños'), ('Patio', 'Patio'), ('Piscina', 'Piscina')], max_length=15),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Luz', 'Luz'), ('Agua', 'Agua'), ('Alcantarillado', 'Alcantarillado')], max_length=15),
        ),
    ]
